### ISSUE TITLE
wrong cellid for oceania/asia lat/lng

### ISSUE THREAD

**Issue by waryas** [coolaj86/s2-geometry-javascript#8] opened 2016-07-31 05:15 UTC
lat=35.67628696987912&lng=139.71965789794925

it gives 6921150643923058688 (or this is one of the neighbors), if you check on s2map, this is about 100km east of japan even though the above coordinate should be tokyo.

**Comment by coolaj86** [comment] 2016-07-31 05:29
Duplicate of https://github.com/coolaj86/s2-geometry-javascript/issues/6

I could use some help on this.

In that issue I've listed some debugging values for another lat/lng that give a bad cell id.

I've also created a file that outputs the various internal values (but I haven't checked yet that they match or don't match the correct ones in the issue):
https://github.com/coolaj86/s2-geometry-javascript/blob/master/tests/debug.js

Would you spend some time to debug a little and see if you can find where the conversion is going wrong?

**Comment by coolaj86** [comment] 2016-07-31 05:30
Here are the correct values (using golang's geo/s2 library):

```
f 3
u -0.9410862997486952
v -0.8474719924531028
i 23989781
j 63280597
lat lng: 35.67628696987912   139.71965789794925
uint64 6924439023356215296
quadkey 3/000030101210311
token 60188c9ac
```

**Comment by waryas** [comment] 2016-07-31 10:33
I'll try to help but my s2 knowledge is limited as the original code is really badly documented imo.

**Comment by coolaj86** [comment] 2016-07-31 12:24
Same here. It's a `console.log()` job. You just trace through the function stack with the old eyeballs and log values and see if you can figure out where the values start to be different.

Once that's done the problem will probably be an issue with padding - like where there should be leading `0`s to a number - or a bad `if` - like somewhere that `0` should be considered truthy because it's a valid result.

**Comment by prusswan** [comment] 2016-08-01 14:29
just want to clarify: cellid <-> latlng conversions should be reversible? So it should always be possible to get back latlng after converting it into cellid?

**Comment by coolaj86** [comment] 2016-08-01 14:59
Yes, but you do lose precision.

If you have coordinates such as `35.67628696987912,139.71965789794925` that's overly specific. You can expect something more like `35.676287,139.719658` to come back.

**Comment by waryas** [comment] 2016-08-01 15:02
6 digits is still perfect

**Comment by prusswan** [comment] 2016-08-02 02:46
But without reversing, how can you check that the latlng -> cellid conversion was correct? 100km corresponds to about 1 degree of difference for latlng, so it is not way off ( but still quite a big difference in absolute terms)

**Comment by coolaj86** [comment] 2016-08-02 03:49
Because we have known-good values:

```
f 3
u -0.9410862997486952
v -0.8474719924531028
i 23989781
j 63280597
lat lng: 35.67628696987912   139.71965789794925
uint64 6924439023356215296
quadkey 3/000030101210311
token 60188c9ac
```

We don't need it to be able to reverse, we just need to see that if we plug in a known-good lat/lng we get back a known-good S2CellId.

This is literally a code monkey `console.log()` job. I spent several hours taking the existing code and getting it to work as good as it does now by just copying code from the golang library, printing out the various representations of the ID (binary, base4, base4) and checking inputs and outputs and intermediate values until I realized how it worked and was able to do the conversion.

Unless someone intimately knows S2 (which only a few Google / Niantic employees do) it's just a matter of checking values and looking to see why it's off.

**Comment by cokeeffekt** [comment] 2016-08-02 04:40
i spent a few hours on this today.... my brain hurts...

so i think our issue lies within the `pointToHilbertQuadList` function

```{ face: 3, ij: [ 23989781, 63280597 ], level: 15 } // input static results to pointToHilbertQuadList
[ 0, 0, 1, 3, 0, 1, 3, 3, 3, 0, 2, 0, 2, 0, 2 ] // returns
[i] T2 ID STRING :  3/001301333020202 6981697699837902848 //quad / s2cellid
shouldbe: 3/000030101210311 // the static result from the out put in a previous comment```

**Comment by coolaj86** [comment] 2016-08-02 05:30
Thanks @cokeeffekt!!!

It's good to see that the IJ looks the same. Were you able to check the UV and ST values? Or did they seem irrelevant?

Here's what I find interesting:

JavaScript can only support 31-bit integers for bitwise operations. If you start doing said operations on 32-bit integers such as `0xFFFFFF << 1` then the sign flips and you have a 31-bit negative integer.

However, I'm pretty sure we're only dealing with 30-bit integers at level 15, so we should be plenty safe.

The solution will probably be to ensure that integers are clamped to 30 bits before doing `&` and `<<` on them or to use long.js or something like that. The next step is to step through step by step and see what happens.

**Comment by prusswan** [comment] 2016-08-02 05:44
I'm trying to compare with the C++ implementation (supposedly the most accurate? correct me if I am wrong)

**Comment by coolaj86** [comment] 2016-08-02 06:01
The golang is easier to read and it's just as accurate:

* https://github.com/golang/geo/blob/master/s2/cellid.go

**Comment by coolaj86** [comment] 2016-08-02 06:25
I looked at another simple implementation and I got the same result. I'm thinking that implementation may not be for a 6-sided cube.

However, the golang function `cellIDFromFaceIJWrap(f, i, j int)` is probably the right one to implement. It does require the use of long.js and it will be tedious to break down step by step (because with long.js you can't put 6 operations on a single line).

I'm thinking that this is a wrapping issue - which totally makes since with something that has '000' at the start - probably right on an edge between two sides of the unfolded cube - a point at which the orientation of the cube changes during its traversal or something like that.

The golang implementation accounts for that and comments on it.

**Comment by cokeeffekt** [comment] 2016-08-02 06:45
ST & UV both seem to be ok... they don't get passed to pointToHilbertQuadList and since i'm using a static I & j they weren't used to create the I, j either.

**Comment by cokeeffekt** [comment] 2016-08-02 06:52
`(function (x, y, z) {

      var pairs = [
        [[0, 3], [1, 0], [3, 1], [2, 0]],
        [[2, 1], [1, 1], [3, 0], [0, 2]],
        [[2, 2], [3, 3], [1, 2], [0, 1]],
        [[0, 0], [3, 2], [1, 3], [2, 3]]
      ];

      var quad = 0,
        pair,
        i = [];
      while (--z >= 0) {
        pair = pairs[quad][(x & (1 << z) ? 2 : 0) | (y & (1 << z) ? 1 : 0)];
        i.push(pair[0]);
        quad = pair[1];
      }
      console.log('HBN', i);
    })(x, y, order);`

also i found / modified this today, to try get another result. Seems to be doing the same thing, and produces the same incorrect numbers...

**Comment by coolaj86** [comment] 2016-08-02 07:25
Our only hope: [`cellIDFromFaceIJWrap(f, i, j int)`](https://github.com/golang/geo/blob/master/s2/cellid.go#L422)

**Comment by DVassilev** [comment] 2016-08-03 05:30
Can confirm I'm experiencing this issue too, any ideas on a fix?

**Comment by prusswan** [comment] 2016-08-03 05:48
my plunker for debugging: https://plnkr.co/edit/YpSqaM?p=preview

**Comment by coolaj86** [comment] 2016-08-03 06:37
It's been fixed, tested, and published as v1.2.6.

https://github.com/coolaj86/s2-geometry-javascript/blob/master/tests/exhaustive.js

Pokemon GO fans may now rejoice! (https://github.com/Armax/Pokemon-GO-node-api/pull/165 is ready to merge!)

**Comment by coolaj86** [comment] 2016-08-03 06:39
This was the fix: https://github.com/coolaj86/s2-geometry-javascript/commit/68274eb677be0338984b0c7d59290ec323c47e67

```
var initialSquare = (face % 2) ? 'd' : 'a';
```

**Comment by DVassilev** [comment] 2016-08-03 07:03
@coolaj86 Just tested with Sydney, Australia coordinates and it returned wrong Cell IDs still.

**Comment by coolaj86** [comment] 2016-08-03 07:29
@DVassilev Double check that you're using v1.2.6 because I've tested about 2 million random locations around the globe and they all match up exactly with s2geometry-node.

* https://github.com/coolaj86/s2-geometry-javascript/blob/master/tests/exhaustive.js

I've also tested a few hundred locations against the golang implementation and they all match as well:

* https://github.com/coolaj86/s2-geometry-javascript/blob/master/tests/js-vs-go.js

Can you give the lat/lng coordinates that you tested and the resultant quadkey?

**Comment by DVassilev** [comment] 2016-08-03 10:47
Sorry for delay. The cell IDs for coordinates in Sydney, Australia. I'll try pull the repo separately and test.

["9158064502539812864", "9158064500392329216", "9158064599176577024", "9158064496097361920", "9158064504687296512", "9158064498244845568", "9158064506834780160", "9158064605619027968", "9158064597029093376", "9158064491802394624", "9158064547636969472", "9158064607766511616", "9158064551931936768", "9158064511129747456", "9158064601324060672", "9158064493949878272", "9158064549784453120", "9158064487507427328", "9158064508982263808", "9158064603471544320", "9158064594881609728", "9158064489654910976", "9158064519719682048", "9158064609913995264", "9158064554079420416"]

**Comment by coolaj86** [comment] 2016-08-03 15:03
@DVassilev You're using an old version. The current version produces these values:

```
-33.87347601637759 151.1954084522501
3/112021111301203
7715420640336936960
```

I've also updated my forks of [PokemonGo-node-api](https://github.com/Daplie/Pokemon-GO-node-api) and [PokemonGO-Map](https://github.com/Daplie/node-pokemap) accordingly (in both the master the master and feature branches).

**Closed by coolaj86** 2016-08-03 15:03 UTC
